"""Phase 4 — Fact model public API."""

from .base import (
    EXTRACTION_METHODS,
    METHOD_LLM,
    METHOD_MANUAL,
    METHOD_METADATA,
    METHOD_PARSER,
    METHOD_REGEX,
    METHOD_RULE,
    METHOD_TABLE,
    METHOD_UNKNOWN,
    ExtractionResult,
    Fact,
    FactLocation,
    FactPeriod,
    FactValue,
    LocationKind,
    PeriodKind,
    ValueKind,
    basis_points,
    boolean_value,
    categorical,
    currency,
    date_value,
    null_value,
    number,
    percentage,
    quarter,
    range_value,
    text_value,
    year,
)
from .identity import fact_id_of

__all__ = [
    "EXTRACTION_METHODS",
    "METHOD_RULE",
    "METHOD_PARSER",
    "METHOD_TABLE",
    "METHOD_REGEX",
    "METHOD_METADATA",
    "METHOD_MANUAL",
    "METHOD_LLM",
    "METHOD_UNKNOWN",
    "ValueKind",
    "PeriodKind",
    "LocationKind",
    "FactValue",
    "FactPeriod",
    "FactLocation",
    "Fact",
    "ExtractionResult",
    "fact_id_of",
    "number",
    "percentage",
    "basis_points",
    "currency",
    "date_value",
    "boolean_value",
    "categorical",
    "text_value",
    "range_value",
    "null_value",
    "year",
    "quarter",
]